### ISSUE TITLE
how to generate training data set in the given format 

### ISSUE THREAD

**Issue by tiru1930** [ArrowLuo/GRACE#3]
Hi 

Thank you for good repo, I want train this model on completely new domain dataset, I have review comment, its aspects and polarity respectively. How do i generate the training and eval data set to use these models.

Token, POS, CHUNCK, Term Label, Sentiment Label, Collapsed Label

I could think of using spacy get token, pos and noun-chunks and sentiment label is what aspect sentiment, but what is term label, how can get this, my understanding is collapsed label - term label + sentiment label

**Comment by ArrowLuo** [comment]
@tiru1930 Term Label contains the `B`, `I`, `O` labels, which are used to aspect terms labeling.
An example is as follows,

> I PRP S-NP O O O
> liked VBD S-VP O O O
> the DT B-NP O O O
> aluminum NN I-NP B_AP POSITIVE B_AP+POSITIVE
> body NN E-NP I_AP POSITIVE I_AP+POSITIVE
> . . O O O O

The `aluminum`  and `body ` have term labels `B_AP` and `I_AP`, respectively.  `_AP` means AsPect term here. It is okay if you want to change to another tag or just keep pure `B` and `I`.

Yes, collapsed label = term label + sentiment label

The POS, CHUNCK, and Collapsed Label are not used in the implementation.
