### ISSUE TITLE
Script for prediction from pretrained model

### ISSUE THREAD

**Issue by tusharkgerg** [ArrowLuo/GRACE#4]
Hi @ArrowLuo 
Thanks for the implementation and I was able to run it successfully on the latest pytorch version (built from source), in order to use cuda 11.2.. and was able to replicate your paper results.

However I'm trying to create a script to use the trained model and make predictions only. Was wondering if you had some script or code that could help, as I was going through the code to patch together something.. 
Cheers.

**Comment by ArrowLuo** [comment]
@tusharkgerg Good idea, but I have no available script for pure inference. I think the [eval](https://github.com/ArrowLuo/GRACE/blob/master/ate_asc_run.py#L569) is what you can refer to if you want to implement the prediction on the trained model.

**Comment by tusharkgerg** [comment]
Gotcha. Yeah have been referring to the eval_epoch function and also the model_init & data loading functions. May need some restructuring so just trying to understand the code for that. Would be great to run some questions by you..

**Comment by tusharkgerg** [comment]
@ArrowLuo could help with the following:
I want to predict sentiment in long documents and I can replace pronouns with their respective terms using a coreference resolution algo. Then take individual sentences and feed into GRACE for predicting sentiment for the aspect terms. Then combine the sentiment classification probabilities for each aspect term in the document.

1. Does the above approach sound the most efficient to you for long documents (ex: news articles)?

2. Can I feed in the aspect terms and predict sentiment only? To do that, would the best method to use GRACE just be to train it on the same domain datasets so that it picks up those aspect terms automatically - and then we just query the results?

**Comment by ArrowLuo** [comment]
@tusharkgerg 
1. It sounds good to me. But not sure about the final performance. The relationship between the sentiment of each aspect term and the sentiment of the long document is not always consistent, and difficult to model.
2. The mentioned approach is a two-stage idea (`feed in the aspect terms and predict sentiment only and just query the results`), which will be faster than training an end-to-end model. It can validate the possibility of the first question above.
