### ISSUE TITLE
复现效果问题

### ISSUE THREAD

**Issue by xce1123** [ArrowLuo/GRACE#5]
您好，参照您的readme参数设置复现三种情况中的结果，但是发现加上VAT之后效果反而变差了，并且其余结果也均比论文中的效果低，请问是为什么呢？readme里面的参数有需要调整的吗？谢谢。

**Comment by ArrowLuo** [comment]
Hi @xce1123, 抱歉才看到。请问差异有多大啊？参数不需要调整。我在lap上重跑了release的code，是可以复现paper的结果的。

**Comment by ArrowLuo** [comment]
reopen if need further discussion.
